config/routes.rb
Rails.application.routes.draw do
  resources :customers, only: [:index, :show]
  resources :products, only: [:index, :show]

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :products, through: :orders
  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :customers, through: :orders
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customers/index.html.erb
<h1>Customers Index</h1>

 <ul>
<% @customers.each do |c| %>

 <li><%= link_to c.name, customer_path(c) %></li>

<% end %>
</ul>

app/views/customers/show.html.erb
<h1> <%= @customer.name %> </h1>

<ol>
<% @customer.products.each do |c| %>
  <li><%= c.name %> - <%= c.price %></li>
<% end %>
</ol> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>Products Index</h1>

<ul>
<% @products.each do |fatman| %>
  <li><%= link_to fatman.name, product_path(fatman) %></li>
<% end %>
</ul>

app/views/products/show.html.erb
<h1> <%= @product.name %> </h1>
<h2> <%= @product.price %> </h2>


<ul>
<% @product.customers.each do |c| %>
   <li><%= c.name %></li>
<% end %>
</ul>